# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    appEmailAddress: maturita@cuba-developer.cz
    appEmailAddressName: VMWI

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    App\Controller\RegistrationController:
        arguments:
            - '%appEmailAddress%'
            - '%appEmailAddressName%'

    # VIRTUAL MACHINE BUNDLE
    VirtualMachineBundle\:
        resource: '../bundles/VirtualMachineBundle/*'
        exclude: '../bundles/VirtualMachineBundle/{Entity}'

    # DIGITAL OCEAN BUNDLE
    DigitalOceanBundle\:
        resource: '../bundles/DigitalOceanBundle/*'
        exclude: '../bundles/DigitalOceanBundle/{Entity}'
    
    DigitalOceanBundle\Manager\SizeManager:
        arguments:
            - '%env(DIGITALOCEAN_TOKEN)%'
    
    DigitalOceanBundle\Manager\ImageManager:
        arguments:
            - '%env(DIGITALOCEAN_TOKEN)%'
    
    DigitalOceanBundle\Manager\VirtualMachineManager:
        arguments:
            - '%env(DIGITALOCEAN_TOKEN)%'

    DigitalOceanBundle\Manager\SSHKeyManager:
        arguments:
            - '%env(DIGITALOCEAN_TOKEN)%'